# syntax=docker/dockerfile:1.10

FROM node:22-bookworm-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable
WORKDIR /app

FROM base AS deps

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN corepack prepare pnpm@12.4.2 --activate \
  && pnpm install --frozen-lockfile

FROM base AS builder

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_* values are public and compiled into the application bundle.
ARG NEXT_PUBLIC_ALLOW_PUBLIC_DOWNLOADS
ARG NEXT_PUBLIC_ALWAYS_SHOW_EXPOSURE_COMP
ARG NEXT_PUBLIC_AWS_S3_BUCKET
ARG NEXT_PUBLIC_AWS_S3_REGION
ARG NEXT_PUBLIC_BLUR_DISABLED
ARG NEXT_PUBLIC_CATEGORY_VISIBILITY
ARG NEXT_PUBLIC_CLOUDFLARE_R2_ACCOUNT_ID
ARG NEXT_PUBLIC_CLOUDFLARE_R2_BUCKET
ARG NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_COLOR_SORT
ARG NEXT_PUBLIC_COLOR_SORT_CHROMA_CUTOFF
ARG NEXT_PUBLIC_COLOR_SORT_STARTING_HUE
ARG NEXT_PUBLIC_DEFAULT_SORT
ARG NEXT_PUBLIC_DEFAULT_THEME
ARG NEXT_PUBLIC_DISABLE_BLUR
ARG NEXT_PUBLIC_DISABLE_UPPERCASE_TITLES
ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_DOMAIN_SHARE
ARG NEXT_PUBLIC_EXHAUSTIVE_SIDEBAR_CATEGORIES
ARG NEXT_PUBLIC_GEO_PRIVACY
ARG NEXT_PUBLIC_GRID_ASPECT_RATIO
ARG NEXT_PUBLIC_GRID_HOMEPAGE
ARG NEXT_PUBLIC_HIDE_CATEGORIES_ON_MOBILE
ARG NEXT_PUBLIC_HIDE_CATEGORY_IMAGE_HOVERS
ARG NEXT_PUBLIC_HIDE_EXIF_DATA
ARG NEXT_PUBLIC_HIDE_KEYBOARD_SHORTCUT_TOOLTIPS
ARG NEXT_PUBLIC_HIDE_SOCIAL
ARG NEXT_PUBLIC_HIDE_TAGS_WITH_ONE_PHOTO
ARG NEXT_PUBLIC_HIDE_TAKEN_AT_TIME
ARG NEXT_PUBLIC_HIDE_TEMPLATE_ATTRIBUTION
ARG NEXT_PUBLIC_HIDE_ZOOM_CONTROLS
ARG NEXT_PUBLIC_HIGH_DENSITY_PREVIEWS
ARG NEXT_PUBLIC_IMAGE_QUALITY
ARG NEXT_PUBLIC_LOCALE
ARG NEXT_PUBLIC_MASONRY_GRID
ARG NEXT_PUBLIC_MATTE_COLOR
ARG NEXT_PUBLIC_MATTE_COLOR_DARK
ARG NEXT_PUBLIC_MATTE_PHOTOS
ARG NEXT_PUBLIC_META_DESCRIPTION
ARG NEXT_PUBLIC_META_TITLE
ARG NEXT_PUBLIC_MINIO_BUCKET
ARG NEXT_PUBLIC_MINIO_DISABLE_SSL
ARG NEXT_PUBLIC_MINIO_DOMAIN
ARG NEXT_PUBLIC_MINIO_PORT
ARG NEXT_PUBLIC_NAV_CAPTION
ARG NEXT_PUBLIC_NAV_SORT_CONTROL
ARG NEXT_PUBLIC_NAV_TITLE
ARG NEXT_PUBLIC_OG_TEXT_ALIGNMENT
ARG NEXT_PUBLIC_PAGE_ABOUT
ARG NEXT_PUBLIC_PRESERVE_ORIGINAL_UPLOADS
ARG NEXT_PUBLIC_PRIORITY_BASED_SORTING
ARG NEXT_PUBLIC_PRO_MODE
ARG NEXT_PUBLIC_SHOW_LARGE_THUMBNAILS
ARG NEXT_PUBLIC_SIDEBAR_TEXT
ARG NEXT_PUBLIC_SITE_ABOUT
ARG NEXT_PUBLIC_SITE_DESCRIPTION
ARG NEXT_PUBLIC_SITE_DOMAIN
ARG NEXT_PUBLIC_SITE_FEEDS
ARG NEXT_PUBLIC_SITE_TITLE
ARG NEXT_PUBLIC_SOCIAL_NETWORKS
ARG NEXT_PUBLIC_STATICALLY_OPTIMIZE_OG_IMAGES
ARG NEXT_PUBLIC_STATICALLY_OPTIMIZE_PAGES
ARG NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTOS
ARG NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTO_CATEGORIES
ARG NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTO_CATEGORY_OG_IMAGES
ARG NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTO_OG_IMAGES
ARG NEXT_PUBLIC_STORAGE_PREFERENCE
ARG NEXT_PUBLIC_TINT_FOLDERS
ARG NEXT_BUILD_WORKERS=2

RUN --mount=type=secret,id=build_database_url,target=/run/secrets/build_database_url,required=true \
  test -s /run/secrets/build_database_url \
  && POSTGRES_URL="$(cat /run/secrets/build_database_url)" \
     DISABLE_POSTGRES_SSL=1 \
     CIRCLE_NODE_TOTAL="$((NEXT_BUILD_WORKERS + 1))" \
     pnpm build

FROM node:22-bookworm-slim AS runner

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

ARG APP_UID=1001
ARG APP_GID=1001

RUN groupadd --non-unique --gid "$APP_GID" nodejs \
  && useradd --uid "$APP_UID" --gid nodejs \
    --no-create-home --home-dir /app --shell /usr/sbin/nologin nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/ops ./ops

RUN mkdir -p /app/.next/cache/images \
  && chown -R nextjs:nodejs /app/.next

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
